name: Deploy API to GitHub Pages

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Pythonのセットアップ
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: スクリプト実行
        run: |
          python main.py  # JSONを分割してgh-pages用データを生成

      - name: GitHub Pagesへデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages  # デプロイするフォルダ
